In [1]:
import pandas as pd
import numpy as np

In [12]:
text = {
	"text": [
		"people watch Aiyug",
		"Aiyug watch Aiyug",
		"People write comment",
		"Aiyug write comment",
	],
	"output": [1, 1, 0, 0]
}

In [13]:
text=pd.DataFrame(text)

In [14]:
text

text  output
0    people watch Aiyug       1
1     Aiyug watch Aiyug       1
2  People write comment       0
3   Aiyug write comment       0

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer(lowercase=True, stop_words='english',binary=True)


In [16]:
bow=cv.fit_transform(text['text'])

In [17]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [19]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [20]:
cv.transform(["Hellon comment my name is govind"]).toarray()

array([[0, 1, 0, 0, 0]])

In [ ]:
# %pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


N grams

In [24]:
from nltk import ngrams
from nltk.tokenize import word_tokenize

text="I love natural language processing"
tokens=word_tokenize(text)
n=3

trigrams=list(ngrams(tokens,n))
print("trigrama:-",trigrams)

trigrama:- [('I', 'love', 'natural'), ('love', 'natural', 'language'), ('natural', 'language', 'processing')]


TF-ITF

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

text=["I love natural language processing","I love machine learning","I love deep learning"]
vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(text)
# print("TF-IDF Matrix:\n", tfidf_matrix.toarray())
features_name=vectorizer.get_feature_names_out()

for doc_index,doc in enumerate(tfidf_matrix.toarray()):
    print("Document:-",doc_index+1)
    for word_index, score in enumerate(doc):
        if score > 0:
            print(f"  {features_name[word_index]}: {score:.4f}")

Document:- 1
  language: 0.5465
  love: 0.3227
  natural: 0.5465
  processing: 0.5465
Document:- 2
  learning: 0.5478
  love: 0.4254
  machine: 0.7203
Document:- 3
  deep: 0.7203
  learning: 0.5478
  love: 0.4254


In [29]:
vectorizer.get_feature_names_out()

array(['deep', 'language', 'learning', 'love', 'machine', 'natural',
       'processing'], dtype=object)

Part of Speech tagging

In [33]:
%pip install spacy

  Using cached spacy-3.8.7-cp311-cp311-win_amd64.whl.metadata (28 kB)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
  Using cached murmurhash-1.0.13-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
  Using cached cymem-2.0.11-cp311-cp311-win_amd64.whl.metadata (8.8 kB)
  Using cached preshed-3.0.10-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
  Using cached thinc-8.3.6-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
  Using cached srsly-2.5.1-cp311-cp311-win_amd64.whl.metadata (20 kB)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
  Using cached weasel-0.4.1-py3-none-any.whl.metadata (4.6 kB)
  Using cached typer-0.16.0-py3-none-any.whl.metadata (15 kB)
  Using cached pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
  Using cached langcodes-3.5.0-py3-none-any.whl.metadata (29 kB)
  Using cached language_data-1.3.0-py3-no

In [34]:
import spacy

In [36]:
pos=spacy.load("en_core_web_sm")

In [37]:
doc=pos("I love natural language processing")

In [38]:
doc.text

'I love natural language processing'

In [40]:
doc[1].pos_

'VERB'

In [42]:
from nltk import PorterStemmer
st=PorterStemmer()
print(st.stem("loving"))

love


In [ ]:
print(st.stem("loving"))
st.stem("loving")

love


'love'