In [ ]:
#numpy
import numpy as np

In [6]:
print(np.__version__)

2.3.1


In [ ]:
#list
lst=[1,2,3,4,5,5,5]
print(lst)
print(type(lst))

[1, 2, 3, 4, 5, 5, 5]
<class 'list'>


In [11]:
#array
arr=np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4 5 5 5]
<class 'numpy.ndarray'>


In [22]:
lst=list(range(1,10))
lst


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create an array of 5 zeros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [15]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 5 evenly spaced numbers between 1 and 10
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.ones((3,3)) #i,j
# Create a 3x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.arange(1,31)
# Display the array from 1 to 30
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# Reshape arr to a compatible shape, e.g., (3, 3) since arr.size == 9
arr.reshape(3, 10)

array([[3, 1, 2],
       [3, 3, 3],
       [3, 3, 1]], dtype=int32)

In [ ]:
arr=np.random.randint(1,5,9)
arr
# arr is a numpy array of 9 random integers between 1 and 4 (inclusive)

array([3, 1, 2, 3, 3, 3, 3, 3, 1], dtype=int32)

In [ ]:
# Create a 2x3 array of random integers between 1 and 4 (inclusive)
arr = np.random.randint(1, 5, (2, 3))
arr

array([[2, 1, 1],
       [2, 2, 3]], dtype=int32)

In [ ]:
arr = np.random.random((3, 4))
# arr is a 3x4 numpy array with random values between 0 and 1
arr

array([[0.66638123, 0.63674591, 0.51746935, 0.69101514],
       [0.94496803, 0.72181888, 0.38748139, 0.20245042],
       [0.86063375, 0.35438252, 0.13849921, 0.58937291]])

In [ ]:
print("array shape:",arr.shape)
print("array size:",arr.size)
print("no. of dimensions:",arr.ndim)
print("dtype of array:",arr.dtype)

array shape: (3, 4)
array size: 12
no. of dimensions: 2
dtype of array: float64


In [40]:
arr.flatten()
# The flatten() method returns a copy of the array collapsed into one dimension

array([0.66638123, 0.63674591, 0.51746935, 0.69101514, 0.94496803,
       0.72181888, 0.38748139, 0.20245042, 0.86063375, 0.35438252,
       0.13849921, 0.58937291])

In [ ]:
# The ravel() method returns a flattened (1D) array, similar to flatten(), but returns a view whenever possible
arr.ravel()

array([0.66638123, 0.63674591, 0.51746935, 0.69101514, 0.94496803,
       0.72181888, 0.38748139, 0.20245042, 0.86063375, 0.35438252,
       0.13849921, 0.58937291])

In [ ]:
# Transpose the array (swap rows and columns)
arr.T

array([[ 0, 12, 24, 36, 48],
       [ 1, 13, 25, 37, 49],
       [ 2, 14, 26, 38, 50],
       [ 3, 15, 27, 39, 51],
       [ 4, 16, 28, 40, 52],
       [ 5, 17, 29, 41, 53],
       [ 6, 18, 30, 42, 54],
       [ 7, 19, 31, 43, 55],
       [ 8, 20, 32, 44, 56],
       [ 9, 21, 33, 45, 57],
       [10, 22, 34, 46, 58],
       [11, 23, 35, 47, 59]])

In [ ]:
arr=np.arange(60).reshape((5,12))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [47]:
#indexing
arr[0]
arr[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
# Selects rows 0 and 1, and columns 1 and 2 from the array 'arr'
arr[0:2,1:3]

array([[ 1,  2],
       [13, 14]])

In [52]:
arr[-1][-1]

np.int64(59)

In [56]:
arr[4][11]

np.int64(59)

In [58]:
arr[4,11:12]

array([59])

In [61]:
#.....replacing.......
arr[-1][-1]=100
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58, 100]])

In [66]:
arr.min()
arr.max()

np.int64(100)

In [67]:
arr=np.arange(225).reshape((5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [68]:
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

3
int64
(5, 15, 3)
225


In [69]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [71]:
arr[0][0][0]

np.int64(0)

In [72]:
arr[0:2,1:3,1:3]

array([[[ 4,  5],
        [ 7,  8]],

       [[49, 50],
        [52, 53]]])

In [74]:
arr[0:6,0,0]

array([  0,  45,  90, 135, 180])

In [ ]:
arr[0:,0,0]

array([  0,  45,  90, 135, 180])

In [89]:
arr1=np.arange(1,10)
arr2=np.arange(11,20)
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1*arr2)
print(arr1*2)
print(arr2+2)
print(arr1/arr2)
print(arr.min())
print(arr.mean())


[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[12 14 16 18 20 22 24 26 28]
[ 11  24  39  56  75  96 119 144 171]
[ 2  4  6  8 10 12 14 16 18]
[13 14 15 16 17 18 19 20 21]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]
0
112.0
